project_id = "zlcyqvjqupnjxyzashej"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.apply-daily-scoring]
verify_jwt = true
