export const ACCESSORY_GAINED_QUOTES: readonly string[] = [
  'Un nouveau signe orne ton pelage.',
  'La forêt reconnaît ce que tu es devenu.',
  'Chaque effort laisse une trace visible.',
  "Ton territoire s'enrichit d'un symbole de plus.",
  'Le sanctuaire retient ce que tu as bâti.',
  'Une marque de plus, une preuve de plus.',
  'Tu portes maintenant ce que tu as mérité.',
  'La meute remarque ce nouvel éclat.',
  'Ce que tu as semé porte enfin ses fruits.',
  "Un fragment de la forêt t'appartient désormais.",
  'Ton hurlement résonne un peu plus loin.',
  'La constance a payé — un nouvel ornement t\'accompagne.',
  'Le sanctuaire s\'illumine d\'un signe nouveau.',
  'Tu as franchi un seuil silencieux mais réel.',
  'Ce trophée raconte ta régularité.',
  'Une rune de plus grave ton chemin.',
  'Le vent porte la nouvelle : tu as progressé.',
  "Ton antre s'enrichit d'un nouvel éclat.",
  'Chaque jour tenu devient une parure.',
  'Tu regardes en arrière et vois le chemin parcouru.',
  'La forêt t\'offre ce que tu as construit.',
  'Un nouveau reflet orne ta silhouette.',
  'Tu as gagné bien plus qu\'un symbole.',
  "Ce n'est pas la chance, c'est la discipline qui brille ici.",
  'Le sanctuaire garde la mémoire de tes efforts.',
  'Un pas de plus, une marque de plus.',
  'Ton pelage change, ta constance ne change pas.',
  'La meute t\'accueille avec un nouveau signe.',
  'Ce que tu portes aujourd\'hui, tu l\'as gagné hier.',
  'Un éclat nouveau rejoint ta collection.',
  'Le territoire s\'agrandit d\'un symbole durable.',
  'Tu as tenu bon, et cela se voit désormais.',
  'Une nouvelle parure honore ta régularité.',
  'Le sanctuaire célèbre ce que tu ne lâches pas.',
  'Chaque habitude tenue devient une trace visible.',
  'Ton chemin s\'orne d\'un nouveau repère.',
  'La forêt n\'oublie jamais ce qui est mérité.',
  'Un talisman de plus veille sur toi.',
  'Tu as ajouté une pierre à ton sanctuaire.',
  'Ce reflet nouveau, c\'est ta persévérance qui parle.',
  'Le loup grandit, et son sanctuaire avec lui.',
  'Une marque de constance vient de naître.',
  'Ton effort silencieux devient visible aujourd\'hui.',
  'La forêt te reconnaît un peu plus.',
  'Ce nouvel ornement porte le nom de ta discipline.',
  'Tu as tissé un fil de plus dans ta légende.',
  'Le sanctuaire s\'épanouit avec toi.',
  'Une nouvelle empreinte s\'ajoute à ton territoire.',
  'Ce que tu tiens aujourd\'hui, garde-le demain.',
  'Ton hurlement porte désormais un peu plus loin.',
];

export const ACCESSORY_LOST_QUOTES: readonly string[] = [
  'Un éclat s\'est estompé, pas ta capacité à le retrouver.',
  'La forêt patiente, elle ne juge pas.',
  'Ce signe s\'efface, mais le chemin pour le reprendre reste ouvert.',
  'Une pause n\'efface pas ce que tu sais faire.',
  'Le sanctuaire attend ton retour, sans rancune.',
  'Ce que tu as perdu, tu peux le regagner.',
  'Le loup recule parfois pour mieux bondir.',
  'Une marque s\'en va, la volonté reste.',
  'Rien n\'est perdu tant que tu reviens.',
  'La meute ne t\'abandonne pas pour un pas de recul.',
  'Ce symbole reviendra dès que tu reprendras le chemin.',
  'Un répit n\'est pas un renoncement.',
  'Le sanctuaire garde une place pour ce que tu retrouveras.',
  'Même le loup le plus sûr connaît des jours plus calmes.',
  'Ce n\'est qu\'une étape en moins, pas une route effacée.',
  'Demain peut déjà commencer à réparer aujourd\'hui.',
  'La forêt repousse toujours après l\'hiver.',
  'Ce que tu as bâti une fois, tu sais le rebâtir.',
  'Un pas en arrière n\'efface pas les pas d\'avant.',
  'Le sanctuaire s\'assombrit un peu, il peut se rallumer.',
  'Ta discipline n\'a pas disparu, elle attend son signal.',
  'Ce recul est un message, pas une sentence.',
  'Le loup fatigué reste un loup.',
  'Une trace s\'efface, le chemin reste tracé.',
  'Tu connais déjà la route pour revenir ici.',
  'Ce n\'est qu\'un creux avant la prochaine montée.',
  'Le sanctuaire ne s\'effondre pas pour un jour manqué.',
  'Ta constance a un rythme, ceci n\'en est qu\'une respiration.',
  'Rien ne t\'empêche de reprendre dès aujourd\'hui.',
  'Ce signe manquant est une invitation, pas un reproche.',
  'La forêt a vu bien des loups revenir plus forts.',
  'Un accessoire s\'éteint, ta capacité à briller non.',
  'Ce recul se corrige un pas après l\'autre.',
  'Le sanctuaire t\'a vu construire, il te verra reconstruire.',
  'Une baisse n\'annule pas tout ce qui précède.',
  'Le vent tourne, il peut tourner à nouveau en ta faveur.',
  'Ce n\'est pas une fin, c\'est un ralentissement.',
  'Le loup qui trébuche reste sur le sentier.',
  'Ta prochaine habitude tenue commence à effacer ceci.',
  'Le sanctuaire retient surtout ceux qui reviennent.',
  'Ce manque se comble dès le prochain effort.',
  'Une marque perdue peut toujours être regagnée.',
  'Le territoire recule un peu, il ne disparaît pas.',
  'Ce jour compte moins que celui d\'après.',
  'La meute attend ton retour, pas ta perfection.',
  'Ce recul n\'est qu\'un chapitre, pas la fin de l\'histoire.',
  'Le sanctuaire connaît les hauts et les bas — il tient bon.',
  'Une pause prolongée n\'est pas une pause définitive.',
  'Ce que le temps a repris, l\'effort peut le rendre.',
  'Le loup ne compte pas les chutes, seulement les retours.',
];

/** Random pick from a quote pool, with an injectable RNG so callers can test determinism. Called by the accessory gain/loss modals to show a motivational line. */
export function pickAccessoryQuote(quotes: readonly string[], random: () => number = Math.random): string {
  const index = Math.min(quotes.length - 1, Math.floor(random() * quotes.length));
  return quotes[index];
}
